version: "2"
services:
   namenode:
      image: flokkr/hadoop:latest
      hostname: namenode
      command: ["hdfs","namenode"]
      ports:
         - 50070:50070
         - 9870:9870
      env_file:
        - ./compose-config
      environment:
          NAMENODE_INIT: "hdfs dfs -chmod 777 /"
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
   datanode:
      command: ["hdfs","datanode"]
      image: flokkr/hadoop:latest
      env_file:
        - ./compose-config
   resourcemanager:
      image: flokkr/hadoop:latest
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./compose-config
   nodemanager:
      image: flokkr/hadoop:latest
      command: ["yarn", "nodemanager"]
      env_file:
        - ./compose-config
