
apiVersion: v1
kind: ConfigMap
metadata:
  name: yarn-config
data:
  MAPRED-SITE.XML_mapreduce.framework.name: yarn
  MAPRED-SITE.XML_yarn.app.mapreduce.am.env: HADOOP_MAPRED_HOME=/opt/hadoop
  MAPRED-SITE.XML_mapreduce.map.env: HADOOP_MAPRED_HOME=/opt/hadoop
  MAPRED-SITE.XML_mapreduce.reduce.env: HADOOP_MAPRED_HOME=/opt/hadoop
  YARN-SITE.XML_yarn.resourcemanager.hostname: yarn-resourcemanager-0.yarn-resourcemanager
  YARN-SITE.XML_yarn.resourcemanager.bind-host: 0.0.0.0
  YARN-SITE.XML_yarn.nodemanager.bind-host: 0.0.0.0
  YARN-SITE.XML_yarn.webapp.ui2.enable: "true"
  YARN-SITE.XML_yarn.nodemanager.pmem-check-enabled: "false"
  YARN-SITE.XML_yarn.nodemanager.delete.debug-delay-sec: "600"
  YARN-SITE.XML_yarn.nodemanager.vmem-check-enabled: "false"
  YARN-SITE.XML_yarn.nodemanager.aux-services: mapreduce_shuffle
  YARN_SITE.XML_yarn.timeline-service.hostname: yarn-timeline-0.yarn-timeline
  YARN_SITE.XML_yarn.log.server.url: http://yarn-timeline-0.yarn-timeline:8188/applicationhistory/logs/
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.maximum-applications: "10000"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.maximum-am-resource-percent: "0.1"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.resource-calculator: org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.queues: default
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.capacity: "100"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.user-limit-factor: "1"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.maximum-capacity: "100"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.state: RUNNING
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.acl_submit_applications: '*'
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.acl_administer_queue: '*'
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.node-locality-delay: "40"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.queue-mappings: ""
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.queue-mappings-override.enable: "false"
  YARN-SITE.XML_yarn.nodemanager.disk-health-checker.max-disk-utilization-per-disk-percentage: "99.0"
